[package]
name = "french-suited-playing-cards"
version = "0.1.0"
edition = "2022"
description = "Implementation of objects commonly used in games using french-suited playing cards. "
license = "MIT"


[dependencies]
rand = "0.8.5"
